"use client";
import { useEffect, useRef, useState } from "react";
import OmMark from "./OmMark";
type Theme="obsidian"|"graphite"|"light";
export default function AppEnhancements(){
 const[theme,setTheme]=useState<Theme>(()=>(typeof window!=="undefined"?localStorage.getItem("om_theme"):null) as Theme||"obsidian"),[petOpen,setPetOpen]=useState(false),[petTask,setPetTask]=useState(""),[badge,setBadge]=useState(0);const input=useRef<HTMLInputElement>(null);
 useEffect(()=>{document.documentElement.dataset.omTheme=theme;localStorage.setItem("om_theme",theme)},[theme]);
 const cycleTheme=()=>setTheme(t=>t==="obsidian"?"graphite":t==="graphite"?"light":"obsidian");
 const backup=()=>{const data:Record<string,string>={};for(let i=0;i<localStorage.length;i++){const k=localStorage.key(i);if(k?.startsWith("om_"))data[k]=localStorage.getItem(k)||""}const blob=new Blob([JSON.stringify({product:"OM Personal AI Universe",version:1,exportedAt:new Date().toISOString(),data},null,2)],{type:"application/json"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=`om-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(url)};
 const restore=(file:File)=>{const reader=new FileReader();reader.onload=()=>{try{const parsed=JSON.parse(String(reader.result));Object.entries(parsed.data||{}).forEach(([k,v])=>{if(k.startsWith("om_"))localStorage.setItem(k,String(v))});location.reload()}catch{alert("This is not a valid OM backup.")}};reader.readAsText(file)};
 const submit=async()=>{const task=petTask.trim();if(!task)return;try{const response=await fetch("/api/records",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({section:"ai-kanban",title:task,detail:"Queued by floating OM · execution requires an owned worker"})});if(!response.ok)throw new Error();setBadge(b=>b+1);setPetTask("")}catch{alert("OM could not save this task to the private database.")}};
 return <><div className="global-tools"><button onClick={cycleTheme} title={`Theme: ${theme}`} aria-label="Cycle OM theme">◐</button><button onClick={backup} title="Export OM backup">⇩</button><button onClick={()=>input.current?.click()} title="Import OM backup">⇧</button><input ref={input} hidden type="file" accept=".json,application/json" onChange={e=>e.target.files?.[0]&&restore(e.target.files[0])}/></div><div className={`global-pet ${petOpen?"open":""}`}><button className="pet-core" onClick={()=>setPetOpen(!petOpen)} aria-label="Open OM widget"><OmMark/>{badge>0&&<em>{badge}</em>}</button>{petOpen&&<div className="pet-task"><div className="pet-heading"><OmMark/><div><strong>OM is ready</strong><small>Private capability console</small></div></div><div className="om-capabilities"><span><i/>Local routing</span><span><i/>Durable memory</span><span className="setup"><i/>Edge worker setup</span></div><input autoFocus value={petTask} onChange={e=>setPetTask(e.target.value)} onKeyDown={e=>e.key==="Enter"&&submit()} placeholder="Give OM a task…"/><button onClick={submit}>Queue private task →</button></div>}</div></>
}
