"use client";
import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import SovereignSetup from "./SovereignSetup";
import FeatureVault from "./FeatureVault";
import OmMark from "./OmMark";
type Task={id:number;title:string;lane:"Backlog"|"Running"|"Review"|"Done";agent:string};
type Note={id:number;title:string;body:string;kind:"Note"|"Prompt"|"Finding"};
const sections=[["⌂","Command Center"],["✣","Feature Vault"],["▥","AI Kanban"],["⌁","Project Tracker"],["▤","Keep Notes"],["✦","My Findings"],["⌘","Prompt Vault"],["◉","Private Browser"],["♫","Audio Deck"],["⌑","NotebookLM"],["⬡","Integrations"],["▣","Git Selfhost"],["⬢","Ubuntu Server"],["◇","Marketplace"],["⚙","Sovereign Setup"]];
const initialTasks:Task[]=[{id:1,title:"Wire local model health checks",lane:"Running",agent:"Router-01"},{id:2,title:"Index project notes into memory",lane:"Review",agent:"Memory-02"},{id:3,title:"Verify private storage backup",lane:"Backlog",agent:"Vault-01"},{id:4,title:"Publish OM workspace checkpoint",lane:"Done",agent:"Deploy-01"}];
const initialNotes:Note[]=[{id:1,title:"Sovereign rule",body:"Prefer local execution, explicit approval and encrypted storage.",kind:"Note"},{id:2,title:"Research finding",body:"A device-local control plane keeps credentials away from the hosted UI.",kind:"Finding"},{id:3,title:"Build prompt",body:"Inspect first, make the smallest safe change, test the complete path.",kind:"Prompt"}];
export default function Home(){
 const[active,setActive]=useState("Command Center"),[collapsed,setCollapsed]=useState(true),[mobileOpen,setMobileOpen]=useState(false),[sovereignOpen,setSovereignOpen]=useState(false),[vaultOpen,setVaultOpen]=useState(false);
 const[tasks,setTasks]=useState<Task[]>(()=>{if(typeof window==="undefined")return initialTasks;try{return JSON.parse(localStorage.getItem("om_tasks")||"null")||initialTasks}catch{return initialTasks}}),[notes,setNotes]=useState<Note[]>(()=>{if(typeof window==="undefined")return initialNotes;try{return JSON.parse(localStorage.getItem("om_notes")||"null")||initialNotes}catch{return initialNotes}}),[noteTitle,setNoteTitle]=useState(""),[noteBody,setNoteBody]=useState(""),[noteKind,setNoteKind]=useState<Note["kind"]>("Note");
 const[autoRun,setAutoRun]=useState(true),[playing,setPlaying]=useState(false),[query,setQuery]=useState(""),[toast,setToast]=useState(""),[track,setTrack]=useState(0),[radio,setRadio]=useState(true);
 const playlist=[["Sovereign Radio","OM focus stream · local queue"],["Deep Work Circuit","Public ambient stream"],["Kerala Night Code","Local music library"],["Agent Pulse","Generative focus radio"]];
 const[logs,setLogs]=useState([{time:"Now",agent:"Deploy-01",event:"Advanced “Publish OM workspace checkpoint” to Done",reason:"Production validation returned a verified artifact."},{time:"2m",agent:"Memory-02",event:"Moved note indexing to Review",reason:"12,842 embeddings committed; recall test passed at 94%."},{time:"7m",agent:"Router-01",event:"Started local model health checks",reason:"Primary Ollama endpoint answered; fallback discovery pending."}]);
 useEffect(()=>localStorage.setItem("om_tasks",JSON.stringify(tasks)),[tasks]);useEffect(()=>localStorage.setItem("om_notes",JSON.stringify(notes)),[notes]);
 useEffect(()=>{if(!toast)return;const x=setTimeout(()=>setToast(""),1800);return()=>clearTimeout(x)},[toast]);
 const filtered=useMemo(()=>notes.filter(n=>!query||(`${n.title} ${n.body}`).toLowerCase().includes(query.toLowerCase())),[notes,query]);
 const advance=(id:number)=>{const task=tasks.find(t=>t.id===id);if(!task)return;const next=({Backlog:"Running",Running:"Review",Review:"Done",Done:"Done"} as const)[task.lane];setTasks(c=>c.map(t=>t.id!==id?t:{...t,lane:next}));setLogs(l=>[{time:"Now",agent:task.agent,event:`Advanced “${task.title}” to ${next}`,reason:"Manual approval received; lane transition recorded with local evidence."},...l])};
 const addNote=()=>{if(!noteTitle.trim()&&!noteBody.trim())return;setNotes(n=>[{id:Date.now(),title:noteTitle||"Untitled",body:noteBody,kind:noteKind},...n]);setNoteTitle("");setNoteBody("");setToast(`${noteKind} saved locally`)};
 const install=(name:string)=>setToast(`${name} added to installation queue`);
 return <main className={`om-os ${collapsed?"sidebar-collapsed":""}`}>
  <aside className={`os-sidebar ${mobileOpen?"mobile-open":""}`}>
   <div className="os-brand"><span className="os-mark"><OmMark/></span><div className="nav-copy"><strong>OM</strong><small>Private operating universe</small></div><button onClick={()=>setCollapsed(!collapsed)} aria-label="Collapse sidebar">{collapsed?"›":"‹"}</button></div>
   <button className="new-mission"><span>＋</span><b className="nav-copy">New mission</b></button>
   <Link className="ai-cloud-shortcut" href="/ai-cloud"><span>☁</span><b className="nav-copy">AI Cloud</b><em className="nav-copy">LIVE</em></Link>
   <nav className="os-nav">{sections.map(([icon,label])=>{const href=label==="Command Center"?"/":`/${label.toLowerCase().replaceAll(" ","-")}`;return <Link href={href} key={label} title={collapsed?label:""} className={active===label?"active":""}><span>{icon}</span><b className="nav-copy">{label}</b>{label==="AI Kanban"&&<em className="nav-copy">{tasks.filter(t=>t.lane!=="Done").length}</em>}</Link>})}</nav>
   <div className="privacy-card nav-copy"><span>●</span><div><Link href="/private-mode"><strong>Private mode</strong></Link><Link href="/teammate-backed"><small>Teammate backed</small></Link></div></div>
  </aside>
  <section className="os-main">
   <header className="os-topbar"><button className="mobile-menu" onClick={()=>setMobileOpen(true)}>☰</button><div><small>OM / WORKSPACE</small><strong>{active}</strong></div><div className="top-status"><span><i/> Ubuntu edge live</span><button onClick={()=>setSovereignOpen(true)}>⚙ Configure</button><div className="profile">FF</div></div></header>
   <div className="os-content">
    <section className="welcome-row"><div><p className="gold-kicker">ॐ SOVEREIGN MISSION CONTROL</p><h1>Your private AI workspace is ready.</h1><p>Route tasks through local models, OM sub-agents, owned infrastructure and the services you approve.</p></div><button onClick={()=>setActive("AI Kanban")}>Launch autonomous mission <span>→</span></button></section>
    <section className="health-strip">{[["GOD Router","3 local LLMs","online"],["GOD Memory","12.8k memories","online"],["Edge Node","Ubuntu · 21ms","online"],["Privacy Mesh","Tor + VPN ready","standby"],["Git Forge","Self-host ready","standby"]].map(x=><article key={x[0]}><span className={x[2]}/><div><small>{x[0]}</small><strong>{x[1]}</strong></div></article>)}</section>
    <div className="workspace-grid">
     <section className="board-card"><div className="card-head"><div><small>AUTONOMOUS EXECUTION</small><h2>AI Kanban Board</h2></div><label>Auto-complete<input type="checkbox" checked={autoRun} onChange={e=>setAutoRun(e.target.checked)}/></label></div>
      <div className="kanban">{(["Backlog","Running","Review","Done"] as const).map(lane=><div className="lane" key={lane}><header><span>{lane}</span><em>{tasks.filter(t=>t.lane===lane).length}</em></header>{tasks.filter(t=>t.lane===lane).map(t=><article key={t.id}><p>{t.title}</p><footer><span>ॐ {t.agent}</span>{lane!=="Done"?<button onClick={()=>advance(t.id)}>Advance →</button>:<b>✓ Complete</b>}</footer></article>)}{!tasks.some(t=>t.lane===lane)&&<div className="empty-lane">No tasks</div>}</div>)}</div>
      <div className="agent-ticker"><span className="agent-orb">ॐ</span><div><strong>4 OM sub-agents active</strong><p>{autoRun?"Board updates automatically when agents return verified evidence.":"Automatic task movement is paused."}</p></div><button onClick={()=>setTasks(t=>[...t,{id:Date.now(),title:"New autonomous workspace task",lane:"Backlog",agent:"Planner-01"}])}>＋ Add task</button></div>
     </section>
     <aside className="tracker-card"><div className="card-head"><div><small>SOVEREIGN HEALTH</small><h2>Owned infrastructure</h2></div><span className="score">91</span></div><div className="big-progress health-progress"><i/></div>{[["LLM memory","18.4 / 24 GB",77],["Vector memory","12.8k / 50k",26],["MinIO storage","284 / 1000 GB",28],["IPFS pinned","42.6 GB",43]].map(([n,v,p])=><div className="health-row" key={n as string}><span>{n}</span><strong>{v}</strong><i><em style={{width:`${p}%`}}/></i></div>)}<div className="wallet-health"><span>⬡</span><div><strong>Web3 wallet</strong><p>Local Anvil · chain 31337</p></div><em>Connected</em></div><button className="full-button" onClick={()=>setSovereignOpen(true)}>Run live health checks →</button></aside>
    </div>
    <section className="activity-card"><div className="card-head"><div><small>VERIFIED DECISION STREAM</small><h2>OM sub-agent activity</h2></div><span className="live-log"><i/> Live</span></div><div className="activity-feed">{logs.slice(0,5).map((l,i)=><article key={`${l.agent}-${i}`}><time>{l.time}</time><span className="log-agent">ॐ</span><div><strong>{l.agent}</strong><p>{l.event}</p><small><b>Why:</b> {l.reason}</small></div></article>)}</div></section>
    <div className="lower-grid">
     <section className="notes-card"><div className="card-head"><div><small>KNOWLEDGE VAULT</small><h2>Keep Notes · Prompts · My Findings</h2></div><input className="note-search" placeholder="Search vault…" value={query} onChange={e=>setQuery(e.target.value)}/></div>
      <div className="note-compose"><select value={noteKind} onChange={e=>setNoteKind(e.target.value as Note["kind"])}><option>Note</option><option>Prompt</option><option>Finding</option></select><input placeholder="Title" value={noteTitle} onChange={e=>setNoteTitle(e.target.value)}/><textarea placeholder="Capture an idea, reusable prompt, or research finding…" value={noteBody} onChange={e=>setNoteBody(e.target.value)}/><button onClick={addNote}>Save locally</button></div>
      <div className="note-list">{filtered.slice(0,4).map(n=><article key={n.id}><span className={n.kind.toLowerCase()}>{n.kind}</span><div><strong>{n.title}</strong><p>{n.body}</p></div><button onClick={()=>setNotes(all=>all.filter(x=>x.id!==n.id))}>×</button></article>)}</div>
     </section>
     <section className="services-card"><div className="card-head"><div><small>PRIVATE SERVICES</small><h2>Network, code & compute</h2></div><button onClick={()=>setSovereignOpen(true)}>Manage</button></div>
      <div className="service-grid">{[["◉","Tor Router","Onion browser · isolated circuit","Connect"],["◆","Private VPN","WireGuard mesh · kill switch","Enable"],["▣","Git Forge","Gitea self-host · local repos","Install"],["⬢","Ubuntu Server","Docker engine · live console","Open"],["⌬","Antigravity IDE","Agentic IDE workspace","Launch"],["⌑","NotebookLM","Source-grounded notebook bridge","Connect"]].map(s=><article key={s[1]}><span>{s[0]}</span><div><strong>{s[1]}</strong><p>{s[2]}</p></div><button onClick={()=>install(s[1])}>{s[3]}</button></article>)}</div>
      <p className="setup-note">Service buttons prepare setup actions. Tor, VPN, Docker, Gitea and IDE runtimes must run on your owned Ubuntu host; Google, GitHub and NotebookLM require explicit account authorization.</p>
     </section>
    </div>
    <section className="integration-market"><div className="card-head"><div><small>MARKETPLACE</small><h2>Apps & integrations</h2></div><button onClick={()=>setVaultOpen(true)}>Open 50-feature vault</button></div><div className="app-row">{[["G","Google Workspace","Drive · Gmail · Calendar"],["◈","GitHub","Repos · issues · actions"],["N","NotebookLM","Research notebooks"],["◉","Spotify","Playlists & playback"],["☁","SoundCloud","Public stream links"],["▧","Docker","Containers & compose"]].map(a=><article key={a[1]}><span>{a[0]}</span><div><strong>{a[1]}</strong><p>{a[2]}</p></div><button onClick={()=>install(a[1])}>＋</button></article>)}</div></section>
   </div>
  </section>
  <div className="mini-player expanded-player"><button onClick={()=>setPlaying(!playing)}>{playing?"Ⅱ":"▶"}</button><div className="album">ॐ</div><div className="track"><strong>{playlist[track][0]}</strong><span>{playlist[track][1]}</span></div><div className="wave"><i/><i/><i/><i/><i/><i/></div><button title="Previous" onClick={()=>setTrack((track+playlist.length-1)%playlist.length)}>‹</button><button title="Next" onClick={()=>setTrack((track+1)%playlist.length)}>›</button><button className={radio?"radio-on":""} title="Radio mode" onClick={()=>setRadio(!radio)}>⌁</button><div className="queue-pop"><strong>Up next</strong>{playlist.map((p,i)=><button className={i===track?"current":""} key={p[0]} onClick={()=>setTrack(i)}>{i===track?"▶":"♫"} {p[0]}</button>)}</div></div>
  {toast&&<div className="os-toast">✓ {toast}</div>}{mobileOpen&&<button className="nav-scrim" aria-label="Close menu" onClick={()=>setMobileOpen(false)}/>}
  <SovereignSetup open={sovereignOpen} onClose={()=>setSovereignOpen(false)}/>
  <FeatureVault open={vaultOpen} onClose={()=>setVaultOpen(false)} onLaunch={name=>{setVaultOpen(false);setToast(`${name} opened in OM workspace`)}}/>
 </main>
}
