"use client";
import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
const scores=[["Product / UI",9],["Frontend",9],["AI routing",6],["Backend / API",8],["Persistence",9],["Agent execution",4],["Security",8],["Self-hosting",6],["Testing / ops",6]] as const;
const phases=[["Stabilize the repository","Build validation, structured logs, health probes and removal of synthetic responses"],["Authentication + durable database","PostgreSQL, sessions, Argon2id, OAuth, RBAC and attributed audit events"],["GOD Model Router","Ollama discovery, vLLM/cloud adapters, streaming, budgets and circuit breakers"],["GOD Memory","PostgreSQL + Qdrant, embeddings, hybrid retrieval, deduplication and citations"],["Mission + agent runtime","Planner, scheduler, worker leases, idempotency, approvals and risk policies"],["Secure edge execution","mTLS node daemon, rootless containers, seccomp, quotas and sandboxing"],["Storage, Git + Web3","MinIO service accounts, Gitea, RPC allowlists and transaction simulation"],["Authorized integrations","GitHub, Google Workspace, Spotify and encrypted connector tokens"],["Private browser, Tor + VPN","Isolated Chromium, Tor SOCKS, WireGuard, DNS leak protection and kill switch"],["Product completeness","Wire every UI module to measured APIs, test degraded modes and remove placeholders"]] as const;
const criteria=["UI status reflects measured backend state","Notes, tasks and memory survive browser loss","Local-only AI traffic is provably local","Agents use durable jobs and idempotent transitions","Sensitive actions require server-enforced approval","Edge execution is sandboxed","Secrets are encrypted and rotatable","Every action has an attributable audit record","Backups restore successfully","Multi-user isolation is tested","Offline and degraded modes are explicit","No synthetic response is presented as real output"];
const issues=[["Local model router needs an owned endpoint","blocked"],["Agent execution needs an owned sandbox worker","blocked"],["Secrets vault and rotation not connected","critical"],["Automated restore and isolation tests incomplete","open"]];
type Health={measuredAt:string;database:{connected:boolean;records:number};audit:{enabled:boolean;count:number;recent:{id:string;action:string;detail:string;createdAt:string}[]};security:{ownerIsolation:boolean;sameOriginWrites:boolean;inputValidation:boolean;syntheticFallbacks:boolean}};
export default function ProductionReadiness(){
 const [done,setDone]=useState<number[]>([]),[checks,setChecks]=useState<number[]>([]),[health,setHealth]=useState<Health|null>(null);
 useEffect(()=>{const id=requestAnimationFrame(()=>{try{setDone(JSON.parse(localStorage.getItem("om_readiness_phases")||"[]"));setChecks(JSON.parse(localStorage.getItem("om_readiness_checks")||"[]"))}catch{}});return()=>cancelAnimationFrame(id)},[]);
 useEffect(()=>{localStorage.setItem("om_readiness_phases",JSON.stringify(done));localStorage.setItem("om_readiness_checks",JSON.stringify(checks))},[done,checks]);
 useEffect(()=>{fetch("/api/health",{cache:"no-store"}).then(async r=>{if(!r.ok)throw new Error();return r.json()}).then(setHealth).catch(()=>setHealth(null))},[]);
 const overall=useMemo(()=>Math.round(scores.reduce((n,x)=>n+x[1],0)/scores.length*10)/10,[]),toggle=(n:number,set:(v:number[])=>void,vals:number[])=>set(vals.includes(n)?vals.filter(x=>x!==n):[...vals,n]);
 const services=[["OM web workspace","measured","online"],["Owner authentication",health?"verified":"unverified",health?"online":"offline"],["OM D1 database",health?.database.connected?`${health.database.records} records`:"unavailable",health?.database.connected?"online":"offline"],["Audit trail",health?.audit.enabled?`${health.audit.count} recent events`:"unavailable",health?.audit.enabled?"online":"offline"],["Ollama / vLLM","not connected","offline"],["Qdrant","not connected","offline"],["MinIO","setup required","warn"],["Edge node","authorization required","warn"]];
 return <main className="readiness-shell"><header className="readiness-top"><Link href="/">‹ Command Center</Link><div><span>OM / DELIVERY CONTROL</span><h1>Production Readiness</h1><p>Measured truth, target architecture and an executable path to a fully functional sovereign workspace.</p></div><Link className="readiness-config" href="/sovereign-setup">Configure stack →</Link></header>
 <section className="readiness-summary"><div className="readiness-score"><div><strong>{overall}/10</strong><span>current readiness</span></div></div><div className="readiness-breakdown">{scores.map(([label,value])=><article key={label}><span>{label}</span><b>{value}/10</b><i><em style={{width:`${value*10}%`}}/></i></article>)}</div></section>
 <section className="readiness-grid"><article className="readiness-card"><header><div><small>BLOCKERS</small><h2>Critical work</h2></div><b>{issues.length} open</b></header>{issues.map(([name,state])=><p key={name}><span>{name}</span><em className={state}>{state}</em></p>)}</article><article className="readiness-card"><header><div><small>REAL HEALTH PROBE</small><h2>Service status</h2></div><b>{health?"4/8 measured":"probe failed"}</b></header>{services.map(([name,state,tone])=><p key={name}><span>{name}</span><em className={tone}>{state}</em></p>)}<small className="readiness-note">Measured {health?new Date(health.measuredAt).toLocaleString():"health endpoint unavailable"}. External services stay offline until authenticated probes succeed.</small></article></section>
 <section className="readiness-card readiness-plan"><header><div><small>IMPLEMENTATION PLAN</small><h2>10 delivery phases</h2></div><b>{done.length}/10 tracked complete</b></header><div>{phases.map(([name,desc],i)=><button key={name} onClick={()=>toggle(i,setDone,done)} className={done.includes(i)?"complete":""}><i>{done.includes(i)?"✓":i}</i><span><strong>Phase {i} — {name}</strong><small>{desc}</small></span><em>{done.includes(i)?"complete":"mark complete"}</em></button>)}</div><footer>Planning baseline: 12–18 weeks for one engineer, or 6–10 weeks for a focused team of 3–4. Validate after Phase 0.</footer></section>
 <section className="readiness-grid readiness-lower"><article className="readiness-card"><header><div><small>CURRENT + TARGET SYSTEM</small><h2>Production architecture</h2></div><b>zero-trust</b></header><div className="architecture-legend"><span><i className="online"/> Verified now</span><span><i/> Sovereign target</span></div><pre>{`CURRENT HOSTED LAYER · VERIFIED\nWeb UI → Owner-authenticated OM API\n  ├─ D1 · workspace records\n  ├─ Per-owner isolation\n  └─ Attributed audit events\n\nSOVEREIGN RUNTIME · TARGET / NOT CONNECTED\nWeb / Desktop UI\n  └─ Authenticated OM Gateway\n     ├─ PostgreSQL · users, tasks, audit\n     ├─ Redis · queues and leases\n     ├─ Qdrant · semantic memory\n     ├─ MinIO · files and backups\n     ├─ GOD Router\n     │  ├─ Ollama / vLLM · local\n     │  └─ Cloud models · explicit opt-in\n     └─ Sandbox Worker → Owned Edge Node\n        └─ Hash-chained audit log`}</pre></article><article className="readiness-card readiness-definition"><header><div><small>DEFINITION OF DONE</small><h2>Fully functional means</h2></div><b>{checks.length}/12 verified</b></header>{criteria.map((name,i)=><label key={name}><input type="checkbox" checked={checks.includes(i)} onChange={()=>toggle(i,setChecks,checks)}/><span>{name}</span></label>)}<small className="readiness-note">Owner-tracked assertions require evidence from real services and tests before production sign-off.</small></article></section></main>
}
