"use client";
import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import AICloud from "./AICloud";
import ProductionReadiness from "./ProductionReadiness";
import SelfHostingGuide from "./SelfHostingGuide";
import GitHubLaunch from "./GitHubLaunch";
const nav=[["⌂","Command Center","/"],["✣","Feature Vault","/feature-vault"],["▥","AI Kanban","/ai-kanban"],["⌁","Project Tracker","/project-tracker"],["▤","Keep Notes","/keep-notes"],["✦","My Findings","/my-findings"],["⌘","Prompt Vault","/prompt-vault"],["◉","Private Browser","/private-browser"],["♫","Audio Deck","/audio-deck"],["⌑","NotebookLM","/notebooklm"],["⬡","Integrations","/integrations"],["▣","Git Selfhost","/git-selfhost"],["⬢","Ubuntu Server","/ubuntu-server"],["◇","Marketplace","/marketplace"],["⚙","Sovereign Setup","/sovereign-setup"],["●","Private Mode","/private-mode"],["♙","Teammate Backed","/teammate-backed"]];
const meta:Record<string,{title:string;kicker:string;desc:string;stats:string[][];items:string[][];action:string}>={
"ai-cloud":{title:"AI Cloud",kicker:"AGENT EXECUTION",desc:"Compose private AI tasks, approve bounded operations, watch execution evidence and probe the sovereign stack.",stats:[["4","Agents"],["2","Approvals"],["5","Stack probes"],["76%","Context"]],items:[["GOD Router","Local model routing · connector ready"],["GOD Memory","Qdrant index · probe available"],["MinIO Local Storage","Configured · owned endpoint"],["Edge Exec Node","Online · explicit approvals"]],action:"Run OM agent"},
"feature-vault":{title:"Feature Vault",kicker:"50 CAPABILITIES",desc:"Search every local-first OM module, inspect delivery state, and launch its workspace.",stats:[["50","Capabilities"],["31","Active"],["9","Beta"],["10","Roadmap"]],items:[["AI & Intelligence","Local LLM, RAG, voice, agents, knowledge graph"],["Privacy & Security","Tor, VPN, E2E encryption, breach detection"],["Storage & Sync","MinIO, IPFS, P2P sync, version history"],["Automation","No-code workflows, scheduling, scraping, forms"]],action:"Launch selected feature"},
"ai-kanban":{title:"AI Kanban",kicker:"AUTONOMOUS DELIVERY",desc:"Plan missions, assign OM sub-agents, and move work only when verification evidence is present.",stats:[["4","Active agents"],["7","Open tasks"],["3","In review"],["18","Completed"]],items:[["Backlog","Audit private browser isolation"],["Running","Router-01 · Discover local models"],["Review","Memory-02 · Verify vector recall"],["Done","Deploy-01 · Publish workspace"]],action:"Create autonomous task"},
"project-tracker":{title:"Project Tracker",kicker:"MISSION PORTFOLIO",desc:"Track milestones, health, dependencies, evidence, owners, and delivery risk across OM projects.",stats:[["8","Projects"],["68%","Overall"],["12","Milestones"],["2","At risk"]],items:[["OM Universe","68% · Control plane expansion"],["Private Runtime","74% · Host wiring"],["Integration Mesh","52% · Auth connectors"],["Sovereign Deploy","61% · Edge validation"]],action:"Add project"},
"keep-notes":{title:"Keep Notes",kicker:"KNOWLEDGE VAULT",desc:"Capture private device-local notes and organize them for later GOD Memory indexing.",stats:[["34","Notes"],["7","Pinned"],["12","Tags"],["Local","Storage"]],items:[["Sovereign rule","Prefer local execution and encrypted storage."],["Deployment checklist","Build, validate, checkpoint, verify."],["Model inventory","Qwen, DeepSeek, Codestral available."],["Research queue","Review owned edge inference options."]],action:"Save note"},
"my-findings":{title:"My Findings",kicker:"RESEARCH LEDGER",desc:"Preserve discoveries with sources, confidence, evidence, and the decision they influenced.",stats:[["18","Findings"],["42","Sources"],["91%","Confidence"],["5","Pending"]],items:[["Local control plane","Credentials should remain on the owned host."],["Vector recall","Hybrid search improved tested recall."],["Network isolation","Kill-switch must fail closed."],["Model routing","Coder specialist wins structured edits."]],action:"Record finding"},
"prompt-vault":{title:"Prompt Vault",kicker:"REUSABLE INTELLIGENCE",desc:"Save versioned prompts with variables, test results, model compatibility and usage history.",stats:[["46","Prompts"],["9","Collections"],["128","Runs"],["94%","Pass rate"]],items:[["Safe implementation","Inspect, minimize, test, report evidence."],["Deep research","Separate claims, sources and uncertainty."],["Code review","Find correctness, security and regression risks."],["Agent planner","Decompose into bounded verified tasks."]],action:"Create prompt"},
"private-browser":{title:"Private Browser",kicker:"ISOLATED NAVIGATION",desc:"Configure onion circuits, DNS protection, container isolation and an explicit VPN kill switch.",stats:[["Tor","Ready"],["VPN","Standby"],["DNS","Locked"],["0","Trackers"]],items:[["Onion circuit","New identity available"],["WireGuard tunnel","Host authorization required"],["DNS over HTTPS","Local resolver configured"],["Browser container","Ephemeral profile ready"]],action:"Open isolated session"},
"audio-deck":{title:"Audio Deck",kicker:"LOCAL MEDIA",desc:"Queue local tracks and approved public streams with radio mode, favorites and device output.",stats:[["24","Tracks"],["4","Stations"],["3","Playlists"],["Local","Library"]],items:[["Sovereign Radio","OM focus stream"],["Deep Work Circuit","Ambient public stream"],["Kerala Night Code","Local library"],["Agent Pulse","Generative focus radio"]],action:"Play queue"},
"notebooklm":{title:"NotebookLM",kicker:"SOURCE NOTEBOOKS",desc:"Prepare source-grounded notebook collections and authorize Google access only when you connect.",stats:[["6","Notebooks"],["38","Sources"],["14","Briefs"],["Auth","Required"]],items:[["OM Architecture","12 sources · indexed"],["Sovereign AI Research","8 sources · ready"],["Ubuntu Edge Runbook","6 sources · updated"],["Private Networking","12 sources · review"]],action:"Connect NotebookLM"},
"integrations":{title:"Integrations",kicker:"CONNECTION MESH",desc:"Manage explicit authorizations for Google products, GitHub, media services and owned endpoints.",stats:[["12","Available"],["4","Local"],["3","Connected"],["5","Setup"]],items:[["Google Workspace","Drive, Gmail, Calendar, Meet, Docs"],["GitHub","Repositories, issues and actions"],["Spotify / SoundCloud","Playback authorization"],["OM Edge APIs","Ollama, Qdrant, MinIO, IPFS"]],action:"Add integration"},
"git-selfhost":{title:"Git Selfhost",kicker:"OWNED SOURCE FORGE",desc:"Operate a Gitea-compatible forge with private repositories, mirrors, actions and encrypted backups.",stats:[["Gitea","Ready"],["8","Repositories"],["3","Runners"],["24m","Last backup"]],items:[["om-universe","main · clean"],["god-router","2 branches · 1 review"],["edge-infra","Compose · protected"],["memory-indexer","main · tests passing"]],action:"Create repository"},
"ubuntu-server":{title:"Ubuntu Server",kicker:"EDGE CONTROL",desc:"Inspect Docker services and prepare bounded host operations without pretending browser controls executed them.",stats:[["Online","Host"],["4","Containers"],["21ms","Latency"],["3d 14h","Uptime"]],items:[["ollama","Running · 11434"],["qdrant","Running · 6333"],["minio","Running · 9000"],["ipfs","Running · 5001"]],action:"Open host console"},
"marketplace":{title:"Marketplace",kicker:"OM MODULES",desc:"Discover installable local modules and connector setup recipes with clear permission boundaries.",stats:[["48","Modules"],["19","Local"],["12","Connectors"],["17","Templates"]],items:[["Antigravity IDE","Agentic development workspace"],["Private Mesh","Tor + WireGuard bundle"],["Media Deck","Local and public audio sources"],["Google Suite","Authorized product connectors"]],action:"Install selected"},
"sovereign-setup":{title:"Sovereign Setup",kicker:"PRIVATE CONTROL PLANE",desc:"Configure local LLM, vector memory, storage, Web3 RPC and edge endpoints stored on this device.",stats:[["7","Endpoints"],["0","Telemetry"],["Local","Secrets"],["Strict","Policy"]],items:[["GOD Router","Ollama · quality-first"],["GOD Memory","Qdrant · local embeddings"],["Owned Storage","MinIO + IPFS"],["Web3 Bridge","Local Anvil JSON-RPC"]],action:"Save private configuration"},
"private-mode":{title:"Private Mode",kicker:"ZERO-TRUST WORKSPACE",desc:"Review privacy guarantees, device storage, network locks, telemetry policy and approval boundaries.",stats:[["100%","Private"],["Locked","Network"],["Off","Telemetry"],["Owner","Access"]],items:[["Device-local state","Notes and preferences remain local"],["Explicit approvals","Sensitive actions never auto-run"],["Network lock","Fail-closed routing policy"],["Owner access","No external visitors"]],action:"Run privacy audit"},
"teammate-backed":{title:"Teammate Backed",kicker:"HUMAN + AGENT TEAM",desc:"Coordinate trusted collaborators, roles, shared agents and review gates without widening access silently.",stats:[["1","Owner"],["0","Guests"],["4","Agents"],["Strict","RBAC"]],items:[["Febin Francis","Owner · full control"],["Router-01","Model routing agent"],["Memory-02","Knowledge indexing agent"],["Deploy-01","Verification and delivery agent"]],action:"Invite trusted teammate"}};
export default function WorkspacePage({slug}:{slug:string}){
 type RecordItem={id:string;title:string;detail:string;status:string};
 const page=meta[slug]||meta["feature-vault"],[collapsed,setCollapsed]=useState(false),[query,setQuery]=useState(""),[message,setMessage]=useState(""),[records,setRecords]=useState<RecordItem[]>(page.items.map((x,i)=>({id:`seed-${i}`,title:x[0],detail:x[1],status:"reference"}))),[sync,setSync]=useState<"loading"|"live"|"error">("loading");
 useEffect(()=>{const controller=new AbortController();fetch(`/api/records?section=${encodeURIComponent(slug)}`,{signal:controller.signal,cache:"no-store"}).then(async r=>{if(!r.ok)throw new Error();const data=await r.json();setRecords(data.records.length?data.records:page.items.map((x,i)=>({id:`seed-${i}`,title:x[0],detail:x[1],status:"reference"})));setSync("live")}).catch(e=>{if(e.name!=="AbortError")setSync("error")});return()=>controller.abort()},[slug,page.items]);
 const filtered=useMemo(()=>records.filter(x=>!query||`${x.title} ${x.detail}`.toLowerCase().includes(query.toLowerCase())),[records,query]);
 const add=async()=>{const title=message.trim();if(!title)return;setSync("loading");try{const response=await fetch("/api/records",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({section:slug,title,detail:"Saved to OM private database"})});const data=await response.json();if(!response.ok)throw new Error(data.error);setRecords(r=>[data.record,...r.filter(x=>!x.id.startsWith("seed-"))]);setMessage("");setSync("live")}catch{setSync("error")}};
 const remove=async(id:string)=>{if(id.startsWith("seed-"))return;const response=await fetch(`/api/records?id=${encodeURIComponent(id)}`,{method:"DELETE"});if(response.ok)setRecords(r=>r.filter(x=>x.id!==id));else setSync("error")};
 if(slug==="ai-cloud")return <AICloud/>;
 if(slug==="production-readiness")return <ProductionReadiness/>;
 if(slug==="self-hosting-guide")return <SelfHostingGuide/>;
 if(slug==="github-launch")return <GitHubLaunch/>;
 return <main className={`route-shell ${collapsed?"route-collapsed":""}`}><aside className="route-sidebar"><div className="route-brand"><span>ॐ</span><div><strong>OM</strong><small>Personal AI Universe</small></div><button onClick={()=>setCollapsed(!collapsed)}>{collapsed?"›":"‹"}</button></div><Link href="/" className="route-new">＋ <b>New mission</b></Link><nav>{nav.map(([icon,label,href])=><Link key={href} href={href} className={(slug==="command-center"&&href==="/")||href===`/${slug}`?"active":""}><span>{icon}</span><b>{label}</b></Link>)}</nav><div className="route-private"><span>●</span><div><strong>Private mode</strong><small>Teammate backed</small></div></div></aside>
 <section className="route-main"><header><div><small>OM / {page.kicker}</small><h1>{page.title}</h1></div><div><span>● Owner authenticated</span><Link href="/sovereign-setup">⚙ Configure</Link><i>FF</i></div></header><div className="route-content"><section className="route-hero"><div><p>{page.kicker}</p><h2>{page.title}</h2><span>{page.desc}</span></div><button onClick={()=>setMessage(page.action)}>{page.action} →</button></section><div className="route-stats">{page.stats.map(s=><article key={s[1]}><strong>{s[0]}</strong><span>{s[1]}</span></article>)}</div><section className="route-work"><div className="route-work-head"><div><small>WORKSPACE · DATABASE {sync.toUpperCase()}</small><h3>{page.title} controls</h3></div><input placeholder="Search this page…" value={query} onChange={e=>setQuery(e.target.value)}/></div><div className="route-items">{filtered.map((x,i)=><article key={x.id}><span>{String(i+1).padStart(2,"0")}</span><div><strong>{x.title}</strong><p>{x.detail}</p></div>{x.status==="reference"?<button onClick={()=>setMessage(x.title)}>Use →</button>:<button onClick={()=>remove(x.id)}>Delete</button>}</article>)}</div><div className="route-composer"><input maxLength={160} placeholder={`Add to ${page.title}…`} value={message} onChange={e=>setMessage(e.target.value)} onKeyDown={e=>{if(e.key==="Enter")add()}}/><button onClick={add} disabled={sync==="loading"}>{sync==="loading"?"Syncing…":"Save securely"}</button></div>{sync==="error"&&<p className="sync-error">Database unavailable. No local fallback was written.</p>}</section><div className="route-columns"><section><small>PRIVATE SERVICES</small><h3>Measured runtime</h3>{[["OM database","Connected"],["Owner identity","Verified"],["Audit events","Enabled"],["External nodes","Setup required"]].map(x=><p key={x[0]}><span>{x[0]}</span><b>{x[1]}</b></p>)}</section><section><small>SECURITY CONTROLS</small><h3>Server enforced</h3>{[["Record ownership","Per user"],["Write origin","Same origin"],["Input limits","Validated"],["Synthetic fallback","Disabled"]].map(x=><p key={x[0]}><span>{x[0]}</span><b>{x[1]}</b></p>)}</section></div></div></section></main>
}
